### ISSUE TITLE
Permission error after creating a new service

### ISSUE THREAD

**Issue by ashishkmishra36** [buildlyio/buildly-cli#23]
After running `./init.sh --create-service django`  on windows the service wizard creates a new service but then displays a permission error 
```
==> We will help you to set up a Micro or Right Size Service :)
Type in the name of your service (e.g.: appointments_service): roomler
==> The Django project "roomler" was successfully created
Traceback (most recent call last):
  File "/code/setup.py", line 6, in <module>
    setup()
  File "/code/service_builder/setup_service.py", line 287, in setup
    _configure_project(name_project)
  File "/code/service_builder/setup_service.py", line 90, in _configure_project
    "'ENGINE': 'django.db.backends.{}'.format(os.environ['DATABASE_ENGINE'])"  # noqa
  File "/code/service_builder/utils.py", line 57, in replace_text
    for line in file:
  File "/usr/local/lib/python3.7/fileinput.py", line 252, in __next__
    line = self._readline()
  File "/usr/local/lib/python3.7/fileinput.py", line 339, in _readline
    os.rename(self._filename, self._backupfilename)
PermissionError: [Errno 1] Operation not permitted: 'roomler/roomler/settings/base.py' -> 'roomler/roomler/settings/base.py.bak'
Docker not configured, installed or running
```
Also after manually setting up the Docker file the  `SECRET_KEY` is missing from the application

OS:
`Windows10 Pro`
CLI Tool : Git Bash
Git Bash Version : git version 2.28.0.windows.1

**Comment by glind** [comment]
This is just requiring docker to be installed
